name: Update works

on:
  workflow_dispatch:

jobs:
  update-works:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
      - run: |
          yarn update-works
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: update-works
          create_branch: true
