name: Update works

on:
  workflow_dispatch:

jobs:
  update-works:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - run: |
          yarn install
      - run: |
          yarn update-works
      - uses: peter-evans/create-pull-request@v5
        with:
          title: Update works
          commit-message: Update works
          branch: update-works
          add-paths: src/data/works.tsv
