name: Update works

on:
  workflow_dispatch:

jobs:
  update-works:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          ref: update-works
      - run: |
          yarn install
      - run: |
          yarn update-works
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: update-works
          create_branch: true
      - uses: peter-evans/create-pull-request@v5
        with:
          title: Update works
          commit-message: Update works
          branch: update-works
